<a href="https://colab.research.google.com/github/KBCoronado/MachineLearning/blob/main/Practica_1_KNN_Frutas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
frutas = pd.read_csv("fruit_data_with_colors.csv")
frutas.head()

,fruit_label,fruit_name,fruit_subtype,mass,width,height,color_score
0,1,apple,granny_smith,192,8.4,7.3,0.55
1,1,apple,granny_smith,180,8.0,6.8,0.59
2,1,apple,granny_smith,176,7.4,7.2,0.60
3,2,mandarin,mandarin,86,6.2,4.7,0.80
4,2,mandarin,mandarin,84,6.0,4.6,0.79


In [6]:
#Seleccion de caracteristicas o variables predictoras o variables independientes
x = frutas[["height", "width", "mass", "color_score"]]
#Variable objetivo o variable a predicir
y = frutas["fruit_name"]

In [7]:
#Dividir dataset
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42)

In [8]:
clasificador_KNN = KNeighborsClassifier(n_neighbors=1)
clasificador_KNN.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento", clasificador_KNN.score(X_train, y_train))


Precision del clasificador en fase de entrenamiento 1.0


In [9]:
y_pred = clasificador_KNN.predict(X_test)
print("Reporte de metricas del clasficador: \n,", classification_report(y_test, y_pred))

Reporte de metricas del clasficador: 
,               precision    recall  f1-score   support

       apple       0.00      0.00      0.00         4
       lemon       1.00      0.60      0.75         5
    mandarin       1.00      1.00      1.00         2
      orange       0.38      0.75      0.50         4

    accuracy                           0.53        15
   macro avg       0.59      0.59      0.56        15
weighted avg       0.57      0.53      0.52        15



In [10]:
print ("Matriz de confusion: \n", confusion_matrix(y_test, y_pred), "\n")

Matriz de confusion: 
 [[0 0 0 4]
 [1 3 0 1]
 [0 0 2 0]
 [1 0 0 3]] 



In [11]:
from sklearn.inspection import permutation_importance
result = permutation_importance(clasificador_KNN, X_test, y_test, n_repeats=30, random_state=42)
importancia = pd.DataFrame ({
    "Variable": x.columns,
    "Importancia Media": result.importances_mean,
    "Desviacion": result.importances_std
}).sort_values("Importancia Media", ascending=False)
print(importancia)

      Variable  Importancia Media  Desviacion
2         mass           0.266667    0.095839
3  color_score          -0.004444    0.016630
0       height          -0.028889    0.063674
1        width          -0.062222    0.048483


In [12]:
import plotly.express as px
fig4 = px.bar(importancia, x="Variable", y="Importancia Media",
              error_y="Desviacion", title="Importancia de caracteristicas (KNN - Permutation Importance)",
              text_auto=".3F", color="Variable")
fig4.update_layout(width=600, height=400)
fig4.show()

In [13]:
clasificador_KNN3 = KNeighborsClassifier(n_neighbors=3)
clasificador_KNN3.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento", clasificador_KNN3.score(X_train, y_train))

Precision del clasificador en fase de entrenamiento 0.8409090909090909


In [14]:
y_pred = clasificador_KNN3.predict(X_test)
print("Reporte de metricas del clasificador: \n", classification_report(y_test, y_pred))
print("Precision:", clasificador_KNN3.score(X_test, y_test))

Reporte de metricas del clasificador: 
               precision    recall  f1-score   support

       apple       0.67      0.50      0.57         4
       lemon       0.50      0.40      0.44         5
    mandarin       1.00      1.00      1.00         2
      orange       0.50      0.75      0.60         4

    accuracy                           0.60        15
   macro avg       0.67      0.66      0.65        15
weighted avg       0.61      0.60      0.59        15

Precision: 0.6


In [15]:
print ("Matriz de confusion:\n", confusion_matrix(y_test, y_pred), "\n")

Matriz de confusion:
 [[2 1 0 1]
 [1 2 0 2]
 [0 0 2 0]
 [0 1 0 3]] 



In [16]:
clasificador_KNN5 = KNeighborsClassifier(n_neighbors=5)
clasificador_KNN5.fit(X_train, y_train)
print("Precision de metricas del clasificador: \n", classification_report(y_test, y_pred))
print("Precision:", clasificador_KNN5.score(X_test, y_test))

Precision de metricas del clasificador: 
               precision    recall  f1-score   support

       apple       0.67      0.50      0.57         4
       lemon       0.50      0.40      0.44         5
    mandarin       1.00      1.00      1.00         2
      orange       0.50      0.75      0.60         4

    accuracy                           0.60        15
   macro avg       0.67      0.66      0.65        15
weighted avg       0.61      0.60      0.59        15

Precision: 0.6


In [17]:
print ("Matriz de confusion:\n", confusion_matrix(y_test, y_pred), "\n")

Matriz de confusion:
 [[2 1 0 1]
 [1 2 0 2]
 [0 0 2 0]
 [0 1 0 3]] 



In [18]:
from numpy import sort_complex
for k in range(1, 20):
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(X_train, y_train)
  print(f"k={k} → Precisión: {knn.score(X_test, y_test):.2f}")

k=1 → Precisión: 0.53
k=2 → Precisión: 0.53
k=3 → Precisión: 0.60
k=4 → Precisión: 0.60
k=5 → Precisión: 0.60
k=6 → Precisión: 0.40
k=7 → Precisión: 0.60
k=8 → Precisión: 0.53
k=9 → Precisión: 0.53
k=10 → Precisión: 0.53
k=11 → Precisión: 0.47
k=12 → Precisión: 0.47
k=13 → Precisión: 0.47
k=14 → Precisión: 0.47
k=15 → Precisión: 0.40
k=16 → Precisión: 0.40
k=17 → Precisión: 0.40
k=18 → Precisión: 0.47
k=19 → Precisión: 0.40


In [19]:
from sklearn.preprocessing import StandardScaler
x = frutas[["height", "width", "mass", "color_score"]]
y = frutas["fruit_name"]
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, stratify=y)
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
knn_scaled = KNeighborsClassifier(n_neighbors=3)
knn_scaled.fit(x_train_scaled, y_train)
y_pred_scaledd = knn_scaled.predict(x_test_scaled)
print("\nReporte de clasificacion")
print(classification_report(y_test, y_pred_scaledd))


Reporte de clasificacion
              precision    recall  f1-score   support

       apple       1.00      0.80      0.89         5
       lemon       1.00      1.00      1.00         4
    mandarin       1.00      1.00      1.00         1
      orange       0.83      1.00      0.91         5

    accuracy                           0.93        15
   macro avg       0.96      0.95      0.95        15
weighted avg       0.94      0.93      0.93        15



In [20]:
print("Matriz de confusión:\n", confusion_matrix(y_test, y_pred_scaledd), "\n")

Matriz de confusión:
 [[4 0 0 1]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 5]] 



In [21]:
from sklearn.inspection import permutation_importance
result = permutation_importance(knn_scaled, x_test_scaled, y_test, n_repeats=30, random_state=42)
importancia = pd.DataFrame ({
    "Variable": x.columns,
    "Importancia Media": result.importances_mean,
    "Desviacion": result.importances_std
}).sort_values("Importancia Media", ascending=False)
print(importancia)

      Variable  Importancia Media  Desviacion
0       height           0.262222    0.080615
1        width           0.188889    0.075195
3  color_score           0.182222    0.103184
2         mass           0.037778    0.061303


In [22]:
import plotly.express as px
fig4 = px.bar(importancia, x="Variable", y="Importancia Media",
              error_y="Desviacion", title="importancia de caracteristicas (KNN - Permutation Importancia)",
              text_auto=".3f", color="Variable")
fig4.update_layout(width=600, height=400)
fig4.show()

In [23]:
frutas = [[5.5, 2.2, 150, 0.70]]
print ("la futa 1 con caracteristicas ", frutas, "es de tipo", knn_scaled.predict(frutas))

la futa 1 con caracteristicas  [[5.5, 2.2, 150, 0.7]] es de tipo ['orange']


In [24]:
frutas = [[5.5, 2.2, 120, 0.70], [2, 2, 160, 0.50 ]]
print("las frutas con caraceristicas ", frutas, "son de tipo:",
      knn_scaled.predict(frutas))


las frutas con caraceristicas  [[5.5, 2.2, 120, 0.7], [2, 2, 160, 0.5]] son de tipo: ['orange' 'orange']
