<a href="https://colab.research.google.com/github/KBCoronado/MachineLearning/blob/main/Practica_3_KNN_en_Prestamos_Lending_Club.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, precision_recall_curve

In [ ]:
prestamos_df = pd.read_csv('lending_club_2007_2011_6_states (1).csv')
prestamos_df.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,...,application_type,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens,hardship_flag,disbursement_method,debt_settlement_flag,debt_settlement_flag_date
0,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN
1,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN
2,3000,3000,3000.0,36 months,18.64,109.43,E,E1,MKC Accounting,9 years,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN
3,5600,5600,5600.0,60 months,21.28,152.39,F,F2,NaN,4 years,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN
4,5375,5375,5350.0,60 months,12.69,121.45,B,B5,Starbucks,< 1 year,...,Individual,0.0,0.0,0.0,0.0,0.0,N,Cash,N,NaN


In [ ]:
prestamos_df["grade_code"] = prestamos_df["grade"].astype("category").cat.codes
prestamos_df["purpose_code"] = prestamos_df["purpose"].astype("category").cat.codes
prestamos_df["addr_state_code"] = prestamos_df["addr_state"].astype("category").cat.codes
prestamos_df["home_ownership_code"] = prestamos_df["home_ownership"].astype("category").cat.codes
prestamos_df["repaid"] = prestamos_df["loan_status"].apply(
    lambda x: 1 if x == "Fully Paid" else 0
)

In [ ]:
X = prestamos_df[['funded_amnt', "int_rate", "grade_code", 'purpose_code', 'addr_state_code',
                  'home_ownership_code', 'annual_inc', 'dti', 'revol_util',
                  'pub_rec_bankruptcies']].fillna(0)
y = prestamos_df["repaid"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((11944, 10), (7964, 10), (11944,), (7964,))

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn1 = KNeighborsClassifier(n_neighbors =1)
knn1.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento", knn1.score(X_train, y_train) )

Precision del clasificador en fase de entrenamiento 1.0


In [ ]:
y_pred = knn1.predict(X_test)
print("\nReporte de métricas del clasificador con 1 vecino: \n",
      classification_report(y_test, y_pred, target_names=["No Pagado","Pagado"]))
print(f'\nMatriz Confusion con 1 vecino:\n', confusion_matrix(y_test, y_pred ))



Reporte de métricas del clasificador con 1 vecino: 
               precision    recall  f1-score   support

   No Pagado       0.17      0.15      0.16      1220
      Pagado       0.85      0.86      0.86      6744

    accuracy                           0.76      7964
   macro avg       0.51      0.51      0.51      7964
weighted avg       0.74      0.76      0.75      7964


Matriz Confusion con 1 vecino:
 [[ 185 1035]
 [ 914 5830]]


In [ ]:
knn5 = KNeighborsClassifier(n_neighbors =5)
knn5.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento", knn5.score(X_train, y_train) )

Precision del clasificador en fase de entrenamiento 0.8614367046215673


In [ ]:
y_pred = knn5.predict(X_test)
print("\nReporte de métricas del clasificador con 5vecinos: \n",
      classification_report(y_test, y_pred, target_names=["No Pagado","Pagado"]))
print(f'\nMatriz de Confusion con 5 vecinos:\n', confusion_matrix(y_test, y_pred ))


Reporte de métricas del clasificador con 5vecinos: 
               precision    recall  f1-score   support

   No Pagado       0.21      0.04      0.06      1220
      Pagado       0.85      0.98      0.91      6744

    accuracy                           0.83      7964
   macro avg       0.53      0.51      0.48      7964
weighted avg       0.75      0.83      0.78      7964


Matriz de Confusion con 5 vecinos:
 [[  43 1177]
 [ 166 6578]]


In [ ]:
knn10 = KNeighborsClassifier(n_neighbors =10)
knn10.fit(X_train, y_train)
print("Precision del clasificador en fase de entrenamiento", knn10.score(X_train, y_train) )


Precision del clasificador en fase de entrenamiento 0.8544876088412592


In [ ]:
y_pred = knn10.predict(X_test)
print("\nReporte de métricas del clasificador con 10vecinos: \n",
      classification_report(y_test, y_pred, target_names=["No Pagado","Pagado"]))
print(f'Matriz de Confusion con 10 vecinos:\n',confusion_matrix(y_test, y_pred ))


Reporte de métricas del clasificador con 10vecinos: 
               precision    recall  f1-score   support

   No Pagado       0.20      0.02      0.03      1220
      Pagado       0.85      0.99      0.91      6744

    accuracy                           0.84      7964
   macro avg       0.52      0.50      0.47      7964
weighted avg       0.75      0.84      0.78      7964

Matriz de Confusion con 10 vecinos:
 [[  19 1201]
 [  77 6667]]


In [ ]:
from sklearn.inspection import permutation_importance
result = permutation_importance(knn10, X_test, y_test, n_repeats=30, random_state=42)
importancia = pd.DataFrame ({
    "Variable": X.columns,
    "Importancia Media": result.importances_mean,
    "Desviacion": result.importances_std
}).sort_values("Importancia Media", ascending=False)
print(importancia)


               Variable  Importancia Media  Desviacion
0           funded_amnt           0.001641    0.001235
6            annual_inc           0.001444    0.001172
8            revol_util           0.000586    0.000429
7                   dti           0.000146    0.000218
2            grade_code           0.000054    0.000077
1              int_rate           0.000033    0.000121
4       addr_state_code           0.000008    0.000107
5   home_ownership_code           0.000000    0.000000
9  pub_rec_bankruptcies           0.000000    0.000000
3          purpose_code          -0.000067    0.000155


In [ ]:
import plotly.express as px
fig4 = px.bar(importancia, x="Variable", y="Importancia Media",
              error_y="Desviacion", title="Importancia de caracteristicas (KNN)-Permutacion importance)",
              text_auto=".3F", color="Variable")
fig4.update_layout(width=800, height=600)
fig4.show()


In [ ]:
from sklearn.preprocessing import StandardScaler
X = prestamos_df[['funded_amnt', "int_rate", "grade_code", 'purpose_code', 'addr_state_code',
                  'home_ownership_code', 'annual_inc', 'dti', 'revol_util',
                  'pub_rec_bankruptcies']].fillna(0)
y = prestamos_df["repaid"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=24, stratify=y)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
knn_scaled = KNeighborsClassifier(n_neighbors=3)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y 3 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado", "Pagado"]))
print ("\nMatriz de confusión con datos normalizados y 3vecinos:\n", confusion_matrix(y_test, y_pred_scaled),"\n")


Reporte de clasificación datos normalizados y 3 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.20      0.09      0.13      1177
      Pagado       0.86      0.94      0.89      6787

    accuracy                           0.81      7964
   macro avg       0.53      0.51      0.51      7964
weighted avg       0.76      0.81      0.78      7964


Matriz de confusión con datos normalizados y 3vecinos:
 [[ 108 1069]
 [ 430 6357]] 



In [ ]:
knn_scaled = KNeighborsClassifier(n_neighbors=5)
knn_scaled.fit(X_train_scaled, y_train)
print("\nReporte de clasificacion datosr normalizados y 5 vecinos:")
print(classification_report (y_test, y_pred_scaled, target_names=["No pagado", "Pagado"]))
print ("\nMatriz de confusión con datos normalizados y 5vecinos:\n", confusion_matrix(y_test, y_pred_scaled),"\n")



Reporte de clasificacion datosr normalizados y 5 vecinos:
              precision    recall  f1-score   support

   No pagado       0.20      0.09      0.13      1177
      Pagado       0.86      0.94      0.89      6787

    accuracy                           0.81      7964
   macro avg       0.53      0.51      0.51      7964
weighted avg       0.76      0.81      0.78      7964


Matriz de confusión con datos normalizados y 5vecinos:
 [[ 108 1069]
 [ 430 6357]] 



In [ ]:
knn_scaled = KNeighborsClassifier(n_neighbors=10)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)
print("\nReporte de clasificación datos normalizados y10 vecinos:")
print(classification_report(y_test, y_pred_scaled, target_names=["No Pagado","Pagado"]))
print ("\nMatriz de confusión con datos normalizados y 10vecinos:\n", confusion_matrix(y_test, y_pred_scaled),"\n")


Reporte de clasificación datos normalizados y10 vecinos:
              precision    recall  f1-score   support

   No Pagado       0.28      0.05      0.09      1177
      Pagado       0.86      0.98      0.91      6787

    accuracy                           0.84      7964
   macro avg       0.57      0.51      0.50      7964
weighted avg       0.77      0.84      0.79      7964


Matriz de confusión con datos normalizados y 10vecinos:
 [[  59 1118]
 [ 152 6635]] 

